//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 逗豆豆.Push2NuGet_VisualStudioPackage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("逗豆豆.Push2NuGet_VisualStudioPackage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 .nuget Folder Was Not Found！ 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_ {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NuGet.exe Not Found In The Folder .nuget ！ 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_NuGetExeNotFound {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_NuGetExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .nuget Folder Was Not Found！ 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_NugetFloderNotFound {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_NugetFloderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NuGet.xml Not Found In The Folder .nuget ！ 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_NugetXmlNotFound {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_NugetXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push2NuGet Error 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_Push2NuGet_Error {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_Push2NuGet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push2NuGet Infomation 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_Push2NuGet_Infomation {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_Push2NuGet_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve NuGet.xml Faild！ 的本地化字符串。
        /// </summary>
        internal static string Push2NuGetVisualStudioPackagePackage_MenuItemCallback_ResolveNugetXmlFaild {
            get {
                return ResourceManager.GetString("Push2NuGetVisualStudioPackagePackage_MenuItemCallback_ResolveNugetXmlFaild", resourceCulture);
            }
        }
    }
}
